-- ============================================================
-- 0063: 시험현황 데이터 운영 DB 동기화 (운영=기준)
-- 운영(koist.ai.kr)의 보안기능시험 72건 + 암호모듈검증 2건을
-- 개발 DB에 그대로 복제하여 운영과 100% 동일하게 맞춤
-- 생성일: 2026-06-30
-- ============================================================

-- [1] 기존 두 카테고리 데이터 전부 삭제 (개발 DB의 옛 69/1건 제거)
DELETE FROM progress_items WHERE category IN ('보안기능시험','암호모듈검증');

-- [2] 운영 데이터 그대로 재삽입 (총 74건)
INSERT INTO progress_items (category, product_name, company, status, assurance_level, cert_type, eval_type, start_date, end_date, note, sort_order) VALUES ('보안기능시험', 'S-Work V3.1', '', '시험진행', '정보보호시스템', '기본시험', '최초신청', NULL, NULL, '', 0);
INSERT INTO progress_items (category, product_name, company, status, assurance_level, cert_type, eval_type, start_date, end_date, note, sort_order) VALUES ('보안기능시험', 'MESIM mHUB V3.0', '', '시험진행', '정보보호시스템', '기본시험', '최초신청', NULL, NULL, '', 0);
INSERT INTO progress_items (category, product_name, company, status, assurance_level, cert_type, eval_type, start_date, end_date, note, sort_order) VALUES ('보안기능시험', 'sDetector v1.0', '', '시험진행', '정보보호시스템', '기본시험', '최초신청', NULL, NULL, '', 0);
INSERT INTO progress_items (category, product_name, company, status, assurance_level, cert_type, eval_type, start_date, end_date, note, sort_order) VALUES ('보안기능시험', 'SubGATE V5.2 N', '', '시험진행', '네트워크장비', '기본시험', '최초신청', NULL, NULL, '', 1);
INSERT INTO progress_items (category, product_name, company, status, assurance_level, cert_type, eval_type, start_date, end_date, note, sort_order) VALUES ('보안기능시험', 'OS6870 Series_8.10.112.R02', '', '발급완료', '네트워크장비', '기본시험', '최초신청', NULL, NULL, NULL, 2);
INSERT INTO progress_items (category, product_name, company, status, assurance_level, cert_type, eval_type, start_date, end_date, note, sort_order) VALUES ('보안기능시험', 'OS6560/6560E Series_8.10.105.R02', '', '발급완료', '네트워크장비', '기본시험', '최초신청', NULL, NULL, NULL, 3);
INSERT INTO progress_items (category, product_name, company, status, assurance_level, cert_type, eval_type, start_date, end_date, note, sort_order) VALUES ('보안기능시험', 'OS9900 Series_8.10.106.R02', '', '발급완료', '네트워크장비', '기본시험', '최초신청', NULL, NULL, NULL, 4);
INSERT INTO progress_items (category, product_name, company, status, assurance_level, cert_type, eval_type, start_date, end_date, note, sort_order) VALUES ('보안기능시험', 'OS6900 Series_8.10.105.R02', '', '발급완료', '네트워크장비', '기본시험', '최초신청', NULL, NULL, NULL, 5);
INSERT INTO progress_items (category, product_name, company, status, assurance_level, cert_type, eval_type, start_date, end_date, note, sort_order) VALUES ('보안기능시험', 'SecureDesk v3.5', '', '발급완료', '정보보호시스템', '간소화 발급', '최초신청', NULL, NULL, NULL, 6);
INSERT INTO progress_items (category, product_name, company, status, assurance_level, cert_type, eval_type, start_date, end_date, note, sort_order) VALUES ('보안기능시험', 'Privacy-i V8.0', '', '발급완료', '정보보호시스템', '간소화 발급', '최초신청', NULL, NULL, NULL, 7);
INSERT INTO progress_items (category, product_name, company, status, assurance_level, cert_type, eval_type, start_date, end_date, note, sort_order) VALUES ('보안기능시험', 'TA-FDM V2.2', '', '발급완료', '정보보호시스템', '간소화 발급', '최초신청', NULL, NULL, NULL, 8);
INSERT INTO progress_items (category, product_name, company, status, assurance_level, cert_type, eval_type, start_date, end_date, note, sort_order) VALUES ('보안기능시험', '지오티_보안스위치_시리즈_V7.0.3', '', '발급완료', '네트워크장비', '간소화 발급', '최초신청', NULL, NULL, NULL, 9);
INSERT INTO progress_items (category, product_name, company, status, assurance_level, cert_type, eval_type, start_date, end_date, note, sort_order) VALUES ('보안기능시험', 'ETK-5000 Series (v2.dev-250928.23.2257)', '', '발급완료', '네트워크장비', '간소화 발급', '최초신청', NULL, NULL, NULL, 10);
INSERT INTO progress_items (category, product_name, company, status, assurance_level, cert_type, eval_type, start_date, end_date, note, sort_order) VALUES ('보안기능시험', 'NUC92B_Series_V100R006B07D002-r111', '', '발급완료', '네트워크장비', '간소화 발급', '최초신청', NULL, NULL, NULL, 11);
INSERT INTO progress_items (category, product_name, company, status, assurance_level, cert_type, eval_type, start_date, end_date, note, sort_order) VALUES ('보안기능시험', 'UBI SAFER-PSM V3.0', '', '발급완료', '정보보호시스템', '간소화 발급', '최초신청', NULL, NULL, NULL, 12);
INSERT INTO progress_items (category, product_name, company, status, assurance_level, cert_type, eval_type, start_date, end_date, note, sort_order) VALUES ('보안기능시험', 'Red Hat OpenShift Virtualization Engine 4', '', '발급완료', '정보보호시스템', '간소화 발급', '최초신청', NULL, NULL, NULL, 13);
INSERT INTO progress_items (category, product_name, company, status, assurance_level, cert_type, eval_type, start_date, end_date, note, sort_order) VALUES ('보안기능시험', 'Logsaver v4.0', '', '발급완료', '정보보호시스템', '간소화 발급', '최초신청', NULL, NULL, NULL, 14);
INSERT INTO progress_items (category, product_name, company, status, assurance_level, cert_type, eval_type, start_date, end_date, note, sort_order) VALUES ('보안기능시험', 'NUC90A_Series_V1.6.7.3-r112', '', '발급완료', '네트워크장비', '간소화 발급', '최초신청', NULL, NULL, NULL, 15);
INSERT INTO progress_items (category, product_name, company, status, assurance_level, cert_type, eval_type, start_date, end_date, note, sort_order) VALUES ('보안기능시험', 'RUCKUS ICX 7850 Series Switch 10.0.10g_cd2_kcc', '', '발급완료', '네트워크장비', '간소화 발급', '최초신청', NULL, NULL, NULL, 16);
INSERT INTO progress_items (category, product_name, company, status, assurance_level, cert_type, eval_type, start_date, end_date, note, sort_order) VALUES ('보안기능시험', 'ARAD2000-48T (ANOS 2.1.6.2)', '', '발급완료', '네트워크장비', '간소화 발급', '최초신청', NULL, NULL, NULL, 17);
INSERT INTO progress_items (category, product_name, company, status, assurance_level, cert_type, eval_type, start_date, end_date, note, sort_order) VALUES ('보안기능시험', 'ARA1000-48T (ANOS 2.1.6.2)', '', '발급완료', '네트워크장비', '간소화 발급', '최초신청', NULL, NULL, NULL, 18);
INSERT INTO progress_items (category, product_name, company, status, assurance_level, cert_type, eval_type, start_date, end_date, note, sort_order) VALUES ('보안기능시험', 'RUCKUS ICX 8200 Series Switch 10.0.10g_cd2_kcc', '', '발급완료', '네트워크장비', '간소화 발급', '최초신청', NULL, NULL, NULL, 19);
INSERT INTO progress_items (category, product_name, company, status, assurance_level, cert_type, eval_type, start_date, end_date, note, sort_order) VALUES ('보안기능시험', 'CloudiA / SynergiA v1.0', '', '발급완료', '정보보호시스템', '간소화 발급', '최초신청', NULL, NULL, NULL, 20);
INSERT INTO progress_items (category, product_name, company, status, assurance_level, cert_type, eval_type, start_date, end_date, note, sort_order) VALUES ('보안기능시험', 'SCP nuri stack Ver 1.0', '', '발급완료', '정보보호시스템', '간소화 발급', '최초신청', NULL, NULL, NULL, 21);
INSERT INTO progress_items (category, product_name, company, status, assurance_level, cert_type, eval_type, start_date, end_date, note, sort_order) VALUES ('보안기능시험', 'RUCKUS ICX 7550 Series Switch 10.0.10g_cd1_kcc', '', '발급완료', '네트워크장비', '간소화 발급', '최초신청', NULL, NULL, NULL, 22);
INSERT INTO progress_items (category, product_name, company, status, assurance_level, cert_type, eval_type, start_date, end_date, note, sort_order) VALUES ('보안기능시험', 'VES-MG24B V1.0', '', '발급완료', '네트워크장비', '간소화 발급', '최초신청', NULL, NULL, NULL, 23);
INSERT INTO progress_items (category, product_name, company, status, assurance_level, cert_type, eval_type, start_date, end_date, note, sort_order) VALUES ('보안기능시험', 'FALCON AUTOMATION PLATFORM v2.16', '', '발급완료', '정보보호시스템', '간소화 발급', '최초신청', NULL, NULL, NULL, 24);
INSERT INTO progress_items (category, product_name, company, status, assurance_level, cert_type, eval_type, start_date, end_date, note, sort_order) VALUES ('보안기능시험', 'SHIELDGate V2.0', '', '발급완료', '정보보호시스템', '간소화 발급', '최초신청', NULL, NULL, NULL, 25);
INSERT INTO progress_items (category, product_name, company, status, assurance_level, cert_type, eval_type, start_date, end_date, note, sort_order) VALUES ('보안기능시험', '실시간 암호화 보안제품 V1.1', '', '발급완료', '정보보호시스템', '간소화 발급', '최초신청', NULL, NULL, NULL, 26);
INSERT INTO progress_items (category, product_name, company, status, assurance_level, cert_type, eval_type, start_date, end_date, note, sort_order) VALUES ('보안기능시험', 'SR Linux 24.10.1 for 7000 Series', '', '발급완료', '네트워크장비', '간소화 발급', '최초신청', NULL, NULL, NULL, 27);
INSERT INTO progress_items (category, product_name, company, status, assurance_level, cert_type, eval_type, start_date, end_date, note, sort_order) VALUES ('보안기능시험', 'TA-STR V2.1', '', '발급완료', '정보보호시스템', '간소화 발급', '최초신청', NULL, NULL, NULL, 28);
INSERT INTO progress_items (category, product_name, company, status, assurance_level, cert_type, eval_type, start_date, end_date, note, sort_order) VALUES ('보안기능시험', 'OS6870 Series_8.10.112.R02 (2)', '', '발급완료', '네트워크장비', '간소화 발급', '최초신청', NULL, NULL, NULL, 29);
INSERT INTO progress_items (category, product_name, company, status, assurance_level, cert_type, eval_type, start_date, end_date, note, sort_order) VALUES ('보안기능시험', 'PacketGo ZTNA 3.0', '', '발급완료', '정보보호시스템', '간소화 발급', '최초신청', NULL, NULL, NULL, 30);
INSERT INTO progress_items (category, product_name, company, status, assurance_level, cert_type, eval_type, start_date, end_date, note, sort_order) VALUES ('보안기능시험', 'F5 BIG-IP r5000 & r10000 제품군', '', '발급완료', '네트워크장비', '간소화 발급', '변경·재승인', NULL, NULL, NULL, 31);
INSERT INTO progress_items (category, product_name, company, status, assurance_level, cert_type, eval_type, start_date, end_date, note, sort_order) VALUES ('보안기능시험', 'TgateSDP V2.0', '', '발급완료', '정보보호시스템', '간소화 발급', '최초신청', NULL, NULL, NULL, 32);
INSERT INTO progress_items (category, product_name, company, status, assurance_level, cert_type, eval_type, start_date, end_date, note, sort_order) VALUES ('보안기능시험', 'zenIE V2.0', '', '발급완료', '네트워크장비', '간소화 발급', '최초신청', NULL, NULL, NULL, 33);
INSERT INTO progress_items (category, product_name, company, status, assurance_level, cert_type, eval_type, start_date, end_date, note, sort_order) VALUES ('보안기능시험', 'ETK-4000B Series (v2.dev-241211.25.1980)', '', '발급완료', '네트워크장비', '간소화 발급', '최초신청', NULL, NULL, NULL, 34);
INSERT INTO progress_items (category, product_name, company, status, assurance_level, cert_type, eval_type, start_date, end_date, note, sort_order) VALUES ('보안기능시험', 'SaferZone USB V10', '', '발급완료', '정보보호시스템', '간소화 발급', '변경·재승인', NULL, NULL, NULL, 35);
INSERT INTO progress_items (category, product_name, company, status, assurance_level, cert_type, eval_type, start_date, end_date, note, sort_order) VALUES ('보안기능시험', 'OS9900 Series_8.10.106.R02 (2)', '', '발급완료', '네트워크장비', '간소화 발급', '최초신청', NULL, NULL, NULL, 36);
INSERT INTO progress_items (category, product_name, company, status, assurance_level, cert_type, eval_type, start_date, end_date, note, sort_order) VALUES ('보안기능시험', 'Summit_arm-33.1.100.133 for Edge Series', '', '발급완료', '네트워크장비', '간소화 발급', '최초신청', NULL, NULL, NULL, 37);
INSERT INTO progress_items (category, product_name, company, status, assurance_level, cert_type, eval_type, start_date, end_date, note, sort_order) VALUES ('보안기능시험', 'onie-33.1.100.133 for Core Series', '', '발급완료', '네트워크장비', '간소화 발급', '최초신청', NULL, NULL, NULL, 38);
INSERT INTO progress_items (category, product_name, company, status, assurance_level, cert_type, eval_type, start_date, end_date, note, sort_order) VALUES ('보안기능시험', 'XGS2220 시리즈 ZyNOS V4.90 20240916-KR', '', '발급완료', '네트워크장비', '간소화 발급', '최초신청', NULL, NULL, NULL, 39);
INSERT INTO progress_items (category, product_name, company, status, assurance_level, cert_type, eval_type, start_date, end_date, note, sort_order) VALUES ('보안기능시험', 'OS6570M Series_8.10.102.R01', '', '발급완료', '네트워크장비', '간소화 발급', '최초신청', NULL, NULL, NULL, 40);
INSERT INTO progress_items (category, product_name, company, status, assurance_level, cert_type, eval_type, start_date, end_date, note, sort_order) VALUES ('보안기능시험', 'Privacy-i V7.0', '', '발급완료', '정보보호시스템', '간소화 발급', '변경·재승인', NULL, NULL, NULL, 41);
INSERT INTO progress_items (category, product_name, company, status, assurance_level, cert_type, eval_type, start_date, end_date, note, sort_order) VALUES ('보안기능시험', 'UQ-KDS-100-A01', '', '발급완료', '정보보호시스템', '간소화 발급', '최초신청', NULL, NULL, NULL, 42);
INSERT INTO progress_items (category, product_name, company, status, assurance_level, cert_type, eval_type, start_date, end_date, note, sort_order) VALUES ('보안기능시험', '이노스마트플랫폼 v11 랜섬웨어탐지/차단보안솔루션', '', '발급완료', '정보보호시스템', '간소화 발급', '최초신청', NULL, NULL, NULL, 43);
INSERT INTO progress_items (category, product_name, company, status, assurance_level, cert_type, eval_type, start_date, end_date, note, sort_order) VALUES ('보안기능시험', 'ATTO ACCESS v2.0', '', '발급완료', '네트워크장비', '간소화 발급', '최초신청', NULL, NULL, NULL, 44);
INSERT INTO progress_items (category, product_name, company, status, assurance_level, cert_type, eval_type, start_date, end_date, note, sort_order) VALUES ('보안기능시험', 'NetMarshal EPL1000 v1.0', '', '발급완료', '네트워크장비', '간소화 발급', '최초신청', NULL, NULL, NULL, 45);
INSERT INTO progress_items (category, product_name, company, status, assurance_level, cert_type, eval_type, start_date, end_date, note, sort_order) VALUES ('보안기능시험', 'INFOSAFER V5.0', '', '발급완료', '정보보호시스템', '간소화 발급', '최초신청', NULL, NULL, NULL, 46);
INSERT INTO progress_items (category, product_name, company, status, assurance_level, cert_type, eval_type, start_date, end_date, note, sort_order) VALUES ('보안기능시험', 'NHM-2408 Series for 3.14.1.1-S', '', '발급완료', '네트워크장비', '간소화 발급', '최초신청', NULL, NULL, NULL, 47);
INSERT INTO progress_items (category, product_name, company, status, assurance_level, cert_type, eval_type, start_date, end_date, note, sort_order) VALUES ('보안기능시험', 'Alteon U22 series (standalone) - 34.0.4.0', '', '발급완료', '네트워크장비', '간소화 발급', '최초신청', NULL, NULL, NULL, 48);
INSERT INTO progress_items (category, product_name, company, status, assurance_level, cert_type, eval_type, start_date, end_date, note, sort_order) VALUES ('보안기능시험', 'ETK-5000B Series (v2.dev-240422.23.1696)', '', '발급완료', '네트워크장비', '간소화 발급', '최초신청', NULL, NULL, NULL, 49);
INSERT INTO progress_items (category, product_name, company, status, assurance_level, cert_type, eval_type, start_date, end_date, note, sort_order) VALUES ('보안기능시험', 'TnD-MIBS v2.0', '', '발급완료', '정보보호시스템', '간소화 발급', '최초신청', NULL, NULL, NULL, 50);
INSERT INTO progress_items (category, product_name, company, status, assurance_level, cert_type, eval_type, start_date, end_date, note, sort_order) VALUES ('보안기능시험', 'Q Care Connect-N N1000 v1.0.0', '', '발급완료', '정보보호시스템', '간소화 발급', '최초신청', NULL, NULL, NULL, 51);
INSERT INTO progress_items (category, product_name, company, status, assurance_level, cert_type, eval_type, start_date, end_date, note, sort_order) VALUES ('보안기능시험', 'TiMOS-24.3.R1 for 7x50 Series', '', '발급완료', '네트워크장비', '간소화 발급', '최초신청', NULL, NULL, NULL, 52);
INSERT INTO progress_items (category, product_name, company, status, assurance_level, cert_type, eval_type, start_date, end_date, note, sort_order) VALUES ('보안기능시험', 'OS9900 Series_8.9.91.R04', '', '발급완료', '네트워크장비', '간소화 발급', '최초신청', NULL, NULL, NULL, 53);
INSERT INTO progress_items (category, product_name, company, status, assurance_level, cert_type, eval_type, start_date, end_date, note, sort_order) VALUES ('보안기능시험', 'U-PRIVACY SAFER V4.0', '', '발급완료', '정보보호시스템', '간소화 발급', '최초신청', NULL, NULL, NULL, 54);
INSERT INTO progress_items (category, product_name, company, status, assurance_level, cert_type, eval_type, start_date, end_date, note, sort_order) VALUES ('보안기능시험', 'Hancome xDB V2.8', '', '발급완료', '정보보호시스템', '간소화 발급', '최초신청', NULL, NULL, NULL, 55);
INSERT INTO progress_items (category, product_name, company, status, assurance_level, cert_type, eval_type, start_date, end_date, note, sort_order) VALUES ('보안기능시험', 'SecureGate CDS V1.0', '', '발급완료', '정보보호시스템', '간소화 발급', '최초신청', NULL, NULL, NULL, 56);
INSERT INTO progress_items (category, product_name, company, status, assurance_level, cert_type, eval_type, start_date, end_date, note, sort_order) VALUES ('보안기능시험', 'Alteon DPDK series (standalone) - 34.0.3.0', '', '발급완료', '네트워크장비', '간소화 발급', '최초신청', NULL, NULL, NULL, 57);
INSERT INTO progress_items (category, product_name, company, status, assurance_level, cert_type, eval_type, start_date, end_date, note, sort_order) VALUES ('보안기능시험', 'CLOUD& v2.5', '', '발급완료', '정보보호시스템', '간소화 발급', '최초신청', NULL, NULL, NULL, 58);
INSERT INTO progress_items (category, product_name, company, status, assurance_level, cert_type, eval_type, start_date, end_date, note, sort_order) VALUES ('보안기능시험', 'VDeX for Virtualization V1.0', '', '발급완료', '정보보호시스템', '간소화 발급', '최초신청', NULL, NULL, NULL, 59);
INSERT INTO progress_items (category, product_name, company, status, assurance_level, cert_type, eval_type, start_date, end_date, note, sort_order) VALUES ('보안기능시험', 'OS6560 Series', '', '발급완료', '네트워크장비', '간소화 발급', '최초신청', NULL, NULL, NULL, 60);
INSERT INTO progress_items (category, product_name, company, status, assurance_level, cert_type, eval_type, start_date, end_date, note, sort_order) VALUES ('보안기능시험', 'SafeCon V3.0', '', '발급완료', '정보보호시스템', '간소화 발급', '최초신청', NULL, NULL, NULL, 61);
INSERT INTO progress_items (category, product_name, company, status, assurance_level, cert_type, eval_type, start_date, end_date, note, sort_order) VALUES ('보안기능시험', 'F5 BIGIP r5000 & r10000 제품군', '', '발급완료', '네트워크장비', '간소화 발급', '최초신청', NULL, NULL, NULL, 62);
INSERT INTO progress_items (category, product_name, company, status, assurance_level, cert_type, eval_type, start_date, end_date, note, sort_order) VALUES ('보안기능시험', 'F5 BIGIP r2000 & r4000 제품군', '', '발급완료', '네트워크장비', '간소화 발급', '최초신청', NULL, NULL, NULL, 63);
INSERT INTO progress_items (category, product_name, company, status, assurance_level, cert_type, eval_type, start_date, end_date, note, sort_order) VALUES ('보안기능시험', 'nNetTrust V2.0', '', '발급완료', '정보보호시스템', '간소화 발급', '최초신청', NULL, NULL, NULL, 64);
INSERT INTO progress_items (category, product_name, company, status, assurance_level, cert_type, eval_type, start_date, end_date, note, sort_order) VALUES ('보안기능시험', 'OS9900 Series', '', '발급완료', '네트워크장비', '간소화 발급', '최초신청', NULL, NULL, NULL, 65);
INSERT INTO progress_items (category, product_name, company, status, assurance_level, cert_type, eval_type, start_date, end_date, note, sort_order) VALUES ('보안기능시험', 'ssBridge V5.0', '', '발급완료', '정보보호시스템', '간소화 발급', '최초신청', NULL, NULL, NULL, 66);
INSERT INTO progress_items (category, product_name, company, status, assurance_level, cert_type, eval_type, start_date, end_date, note, sort_order) VALUES ('보안기능시험', 'SafePC Enterprise V7.0', '', '발급완료', '정보보호시스템', '간소화 발급', '최초신청', NULL, NULL, NULL, 67);
INSERT INTO progress_items (category, product_name, company, status, assurance_level, cert_type, eval_type, start_date, end_date, note, sort_order) VALUES ('보안기능시험', 'TgateSDP V2.0 (2)', '', '발급완료', '정보보호시스템', '간소화 발급', '최초신청', NULL, NULL, NULL, 68);
INSERT INTO progress_items (category, product_name, company, status, assurance_level, cert_type, eval_type, start_date, end_date, note, sort_order) VALUES ('보안기능시험', 'IEUM V2.0', '', '발급완료', '정보보호시스템', '간소화 발급', '최초신청', NULL, NULL, NULL, 69);
INSERT INTO progress_items (category, product_name, company, status, assurance_level, cert_type, eval_type, start_date, end_date, note, sort_order) VALUES ('암호모듈검증', 'MagicCrypto V2.3.0', '㈜드림시큐리티', '발급완료', '1', '소프트웨어', '-', NULL, NULL, '', 0);
INSERT INTO progress_items (category, product_name, company, status, assurance_level, cert_type, eval_type, start_date, end_date, note, sort_order) VALUES ('암호모듈검증', 'AlphaCrypto V1.0', '(주)알파비트', '발급완료', '1', '소프트웨어', '', NULL, NULL, NULL, 1);
